---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# rsatz

<!-- badges: start -->
<!-- badges: end -->

rsatz is a minimal library to simply make fake time series data in a tidy way

## Installation

You can install the released version of rsatz from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("rsatz")
```

## Example

This is a basic example which shows you how to make a very simple data set:

```{r example}
library(rsatz)
library(tidyverse)

generate_signal(7, amplitude = 5) %>% 
  shift_signal(10) %>% 
  add_noise() %>% 
  ggplot(aes(date_time, signal)) +
  geom_line()
```


Or something more complicated.

```{r}
generate_signal(7 * 4 * 12, amplitude = 5) %>% 
  shift_signal(10) %>% 
  make_trend(start_interval = 7 * 4 * 48, strength = 5) %>%
  make_trend(start_interval = 7 * 4 * 48 * 2, strength = -10) %>%
  make_weekends() %>%  
  make_anomalies() %>% 
  add_seasonality() %>% 
  add_noise() %>% 
  ggplot(aes(date_time, signal)) +
  geom_line()
```

